name: Create pull request
inputs:
  github_token:
    required: true
runs:
  using: "composite"
  steps:
      - name: Get issue number
        run: echo "ISSUE_NUMBER=$(echo $GITHUB_REF | cut -d'-' -f1 | cut -d'/' -f4)" >> $GITHUB_ENV
        shell: bash
      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -c 12-)" >> $GITHUB_ENV
        shell: bash
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
         github_token: ${{ inputs.github_token }}
         destination_branch: ${{ github.event.repository.default_branch }}
         pr_title: "Pulling ${{ env.BRANCH_NAME }} into ${{ github.event.repository.default_branch }}"
         pr_body: "Closes #${{ env.ISSUE_NUMBER }}"
         pr_draft: true
