name: Run style check
runs:
  using: "composite"
  steps:
    - name: GitHub Action for npx
      uses: mikeal/npx@1.0.0
    - name: Run style check
      run: npx prettier --check .
      shell: bash
