name: Run style check
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
    - name: Install Surge
      run: npm install --global npx
      shell: bash
    - name: Run style check
      run: npx prettier --check .
      shell: bash
